/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 box.gltf 
Author: DEDROX (https://sketchfab.com/Raghavprasanna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gun-box-free-ac068b496f3248dd8e0bd11bab615de2
Title: Gun box (free)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/box.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.metalBreakup} scale={[8, 8, 8]} position={[0,0,0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.metalBreakup} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.metalBright} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.metalDark} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.metalBreakup} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.metalDark} />
    </group>
  )
}

useGLTF.preload('/box.gltf')
